Corrected Windows Fortran compiler

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -183,18 +183,31 @@ jobs:
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       shell: bash -l {0}
       run: |
-        cmake -B "${{ github.workspace }}/build" \
-          -S "${{ github.workspace }}" \
-          -G "${{ matrix.platform.cmake_generator }}" \
-          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
-          -DCMAKE_CXX_COMPILER=${{ matrix.compilers.cxx }} \
-          -DCMAKE_C_COMPILER=${{ matrix.compilers.c }} \
-          -DTUDAT_BUILD_GITHUB_ACTIONS=${{ matrix.platform.ccache }} \
-          -DTUDAT_BUILD_WITH_TEST_PCH=ON \
-          -DTUDAT_BUILD_WITH_PCH=ON \
-          -DTUDAT_BUILD_WITH_MCD_INTERFACE=ON \
-          -DTUDAT_BUILD_FOR_REDUCED_COMPILE_TIME=ON \
+        conda activate tudat
+
+        cmake_args=(
+          -B "${{ github.workspace }}/build"
+          -S "${{ github.workspace }}"
+          -G "${{ matrix.platform.cmake_generator }}"
+          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
+          -DCMAKE_CXX_COMPILER=${{ matrix.compilers.cxx }}
+          -DCMAKE_C_COMPILER=${{ matrix.compilers.c }}
+          -DTUDAT_BUILD_GITHUB_ACTIONS=${{ matrix.platform.ccache }}
+          -DTUDAT_BUILD_WITH_TEST_PCH=ON
+          -DTUDAT_BUILD_WITH_PCH=ON
+          -DTUDAT_BUILD_WITH_MCD_INTERFACE=ON
+          -DTUDAT_BUILD_FOR_REDUCED_COMPILE_TIME=ON
           -DCMAKE_UNITY_BUILD=ON
+        )
+
+        if [[ -z "${FC:-}" ]]; then
+          echo "::error::Conda did not set FC; cannot build MCD with a compiler-compatible NetCDF Fortran module."
+          exit 1
+        fi
+        echo "Using conda Fortran compiler: ${FC}"
+        cmake_args+=("-DCMAKE_Fortran_COMPILER=${FC}")
+
+        cmake "${cmake_args[@]}"
 
     - name: Debug
       run: |
